#!/bin/bash
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# CEO Morning Brief - 毎朝9:00 JST
# ミュウツー主担当 / ルカリオ(SEO) / ポリゴンZ(改善) / アブソル(リスク)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
source "$SCRIPT_DIR/env_loader.sh"

LOGS_DIR="$SCRIPT_DIR/logs"
METRICS_DIR="$HOME/google_metrics"
TODAY=$(date '+%Y年%m月%d日')
YESTERDAY=$(date -d 'yesterday' '+%Y-%m-%d' 2>/dev/null || date -v-1d '+%Y-%m-%d' 2>/dev/null || echo "")
WEBHOOK="${DISCORD_WEBHOOK:-}"

mkdir -p "$LOGS_DIR"

echo "=== CEO Morning Brief ($TODAY) ==="

# ── 1. 前日サマリー ──
YESTERDAY_KPI=""
if [ -f "$LOGS_DIR/kpi_report_$YESTERDAY.json" ]; then
  YESTERDAY_KPI=$(python3 -c "
import json
with open('$LOGS_DIR/kpi_report_$YESTERDAY.json') as f:
    r = json.load(f)
posts = r.get('posts', {})
tokens = r.get('tokens', {})
errors = r.get('errors', {})
print(f\"投稿: {posts.get('total',0)}本 (成功率: {r.get('success_rate',0):.0%})\")
print(f\"内訳: {posts.get('by_type', {})}\")
print(f\"トークン: {tokens.get('total',0):,} (平均: {tokens.get('avg_per_post',0):,}/本)\")
print(f\"エラー: {errors.get('total',0)}件\")
" 2>/dev/null || echo "KPIデータなし")
else
  YESTERDAY_KPI="KPIデータなし"
fi

# トークンコスト補足（token_report.py から取得）
TOKEN_COST_LINE=$(python3 ~/kpop-ai-system/lib/token_report.py daily "$YESTERDAY" 2>/dev/null | grep "コスト:" || echo "")
if [ -n "$TOKEN_COST_LINE" ]; then
  YESTERDAY_KPI="${YESTERDAY_KPI}
${TOKEN_COST_LINE}"
fi

# ── 2. SEOサマリー ──
SEO_SUMMARY=""
if [ -f "$METRICS_DIR/metrics_yesterday.json" ]; then
  SEO_SUMMARY=$(python3 -c "
import json
with open('$METRICS_DIR/metrics_yesterday.json') as f:
    d = json.load(f)
gsc = d.get('gsc', {})
ga4 = d.get('ga4', {})
adsense = d.get('adsense', {})

# GSC
queries = gsc.get('top_queries', [])
top3 = ', '.join(q['query'] for q in queries[:3]) if queries else 'なし'

# GA4
summary = ga4.get('summary', {})
pv = summary.get('pageviews', '?')
sessions = summary.get('sessions', '?')

# AdSense
earnings = adsense.get('ESTIMATED_EARNINGS', '?')

print(f'PV: {pv} / セッション: {sessions}')
print(f'AdSense: ¥{earnings}')
print(f'Top検索: {top3}')
" 2>/dev/null || echo "SEOデータなし")
else
  SEO_SUMMARY="SEOデータなし"
fi

# ── 3. 特筆事項 ──
NOTABLE=""
# 投稿履歴から異常チェック
if [ -f "$SCRIPT_DIR/logs/post_log.json" ]; then
  NOTABLE=$(python3 -c "
import json
from datetime import date, timedelta
with open('$SCRIPT_DIR/logs/post_log.json') as f:
    log = json.load(f)
yesterday = (date.today() - timedelta(days=1)).isoformat()
counts = log.get('daily_counts', {}).get(yesterday, {})
total = counts.get('total', 0)
notes = []
if total == 0:
    notes.append('⚠ 前日投稿ゼロ')
elif total >= 15:
    notes.append(f'📈 前日投稿{total}本（高稼働）')
if counts.get('revenue', 0) == 0 and total > 0:
    notes.append('⚠ 収益記事ゼロ')
print('\n'.join(notes) if notes else '特になし')
" 2>/dev/null || echo "判定不可")
fi

# 不採算カテゴリチェック
CAT_WARNINGS=$(python3 "$SCRIPT_DIR/lib/category_analyzer.py" unprofitable 2>/dev/null || echo "")
if [ -n "$CAT_WARNINGS" ] && [ "$CAT_WARNINGS" != "不採算カテゴリなし" ]; then
  NOTABLE="${NOTABLE}
${CAT_WARNINGS}"
fi

# ── 4. 健全性チェック ──
HEALTH=$(python3 "$SCRIPT_DIR/lib/human_gate.py" health 2>/dev/null | python3 -c "
import json, sys
d = json.load(sys.stdin)
status = '✅ 正常' if d.get('healthy') else '⚠ 異常あり'
checks = d.get('checks', {})
details = []
for k, v in checks.items():
    icon = '✅' if v.get('healthy') else '❌'
    details.append(f'  {icon} {k}')
print(f'{status}\n' + '\n'.join(details))
" 2>/dev/null || echo "チェック失敗")

# ── ブリーフ組み立て ──
BRIEF="📋 **CEO Morning Brief** - $TODAY

**1. 前日サマリー**
$YESTERDAY_KPI

**2. SEOサマリー**
$SEO_SUMMARY

**3. 特筆事項**
$NOTABLE

**4. システム健全性**
$HEALTH

---
_Generated by ミュウツー (CFO/Data)_"

echo "$BRIEF"

# ── Discord送信 ──
if [ -n "$WEBHOOK" ]; then
  python3 -c "
import requests, sys
msg = sys.argv[1][:1900]
requests.post(sys.argv[2], json={'content': msg}, timeout=10)
" "$BRIEF" "$WEBHOOK" 2>/dev/null && echo "✅ Discord送信完了" || echo "⚠ Discord送信失敗"
fi

# ── ログ保存 ──
echo "$BRIEF" > "$LOGS_DIR/morning_brief_$(date '+%Y%m%d').txt"
echo "=== Brief complete ==="
