#!/usr/bin/env python3
"""x_revival_queue_builder.py — X再投稿キュー生成

過去記事のうち、X投稿から一定期間経過 & 高CTRスコア見込みのものを抽出し
HOOK強化版のtweet textを生成して logs/x_revival_queue.jsonl に書き出す。

実投稿は logs/x_backfill_runner.sh (別生成) で ENABLE_X_POST=1 時のみ実施。

使い方:
  python3 lib/x_revival_queue_builder.py [--limit 20]
"""
from __future__ import annotations
import argparse
import json
import re
import subprocess
import urllib.request
from datetime import datetime, timezone, timedelta
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent
LOGS = BASE / "logs"
OUT_QUEUE = LOGS / "x_revival_queue.jsonl"
OUT_RUNNER = LOGS / "x_backfill_runner.sh"
WP = "https://www.kpopjournal.tokyo"
WP_AUTH = str(Path.home() / ".wp_auth")
JST = timezone(timedelta(hours=9))


def curl_get(path: str):
    cmd = ["curl", "-s", f"{WP}{path}", "-K", WP_AUTH]
    return json.loads(subprocess.check_output(cmd, timeout=30).decode())


def load_jsonl(p: Path) -> list[dict]:
    if not p.exists():
        return []
    out = []
    for line in p.read_text(errors="replace").splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            out.append(json.loads(line))
        except Exception:
            continue
    return out


HOOK_PATTERNS = [
    "【復活】{title_short}",
    "もう一度読まれるべき: {title_short}",
    "見逃してませんか？{title_short}",
    "保存版: {title_short}",
    "K-POPファン必読: {title_short}",
]


def hook_score(body: str) -> int:
    score = 0
    if re.search(r"[0-9]", body):
        score += 25
    if re.search(r"BTS|TWICE|BLACKPINK|IVE|ILLIT|aespa|NewJeans|ENHYPEN|TXT|SEVENTEEN|"
                 r"NCT|ATEEZ|TOP|RIIZE|LE\s*SSERAFIM|EXO|GOT7|MAMAMOO|BIGBANG|G-DRAGON|"
                 r"JIMIN|SHINee|BABYMONSTER", body, re.IGNORECASE):
        score += 25
    if re.search(r"衝撃|電撃|判明|ついに|まさか|速報|記録|驚愕|神|レベチ|解禁|完全|必見|"
                 r"復帰|制覇|初|歴史|快挙|1位|首位|伝説|奇跡|爆発|炎上|暴露|激白", body):
        score += 20
    if re.search(r"→|vs|VS|から|でも|なのに|なぜ|なのか|空白|一転|激変|崩壊|異常|[0-9]+年ぶり", body):
        score += 20
    total = len(body.strip())
    if 120 <= total <= 150:
        score += 10
    return min(score, 100)


def build_tweet(title: str, url: str) -> tuple[str, int]:
    """hook強化版tweet(本文のみ)とscoreを返す。URLはリプライに回す前提で本文には含めない。"""
    title_short = re.sub(r"[【】「」『』]", "", title).strip()
    # 最もscoreの高いパターンを選ぶ
    best = ("", 0)
    for pat in HOOK_PATTERNS:
        candidate = pat.format(title_short=title_short)
        # hashtag 2-3個
        hashtags = "\n\n#KPOP #K_POP #KPOPJournal"
        body = candidate + hashtags
        if len(body) > 280:
            body = candidate[:180] + hashtags
        sc = hook_score(body)
        if sc > best[1]:
            best = (body, sc)
    return best


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--limit", type=int, default=20)
    args = ap.parse_args()

    # 過去の投稿取得
    posts = curl_get(
        f"/wp-json/wp/v2/posts?per_page={args.limit * 3}&orderby=date&order=desc"
        "&_fields=id,title,slug,link,date,categories"
    )

    # 既に X 投稿済みの記事を抽出（x_post.log or title_performance）
    x_log = BASE / "logs" / "x_post.log"
    x_posted = set()
    if x_log.exists():
        for line in x_log.read_text(errors="replace").splitlines():
            m = re.search(r'"post_id"\s*:\s*"?(\d+)', line)
            if m:
                x_posted.add(int(m.group(1)))

    ts = datetime.now(tz=JST).isoformat()
    queued = 0
    skipped_low = 0
    with OUT_QUEUE.open("w") as fp:
        for p in posts:
            if queued >= args.limit:
                break
            pid = p["id"]
            title = p["title"]["rendered"]
            url = p["link"]
            body, sc = build_tweet(title, url)
            if sc < 80:
                skipped_low += 1
                continue
            rec = {
                "queued_at": ts,
                "post_id": pid,
                "slug": p["slug"],
                "title": title,
                "url": url,
                "tweet_text": body,
                "hook_score": sc,
                "reply_url": url,
                "rule": "body only; URL in reply",
                "hashtags": ["KPOP", "K_POP", "KPOPJournal"],
            }
            fp.write(json.dumps(rec, ensure_ascii=False) + "\n")
            queued += 1

    # Runner script
    runner = f"""#!/bin/bash
# x_backfill_runner.sh - generated by x_revival_queue_builder.py
# 実行時は環境変数 ENABLE_X_POST=1 が必須。rate limit のため 1投稿あたり 90 秒待機。
set -e
QUEUE="{OUT_QUEUE}"
LOG="{BASE}/logs/x_backfill_run.log"
POSTER="{BASE}/google_metrics/post_to_x.sh"

if [ "${{ENABLE_X_POST:-0}}" != "1" ]; then
  echo "[x_backfill_runner] ENABLE_X_POST=1 が設定されていないため投稿しません (dry-run)"
  echo "[x_backfill_runner] キュー件数: $(wc -l < \"$QUEUE\")"
  exit 0
fi

echo "=== x_backfill_runner start $(date -Iseconds) ===" | tee -a "$LOG"
COUNT=0
while IFS= read -r line; do
  [ -z "$line" ] && continue
  post_id=$(echo "$line" | python3 -c "import json,sys; print(json.loads(sys.stdin.read()).get('post_id',''))")
  title=$(echo "$line" | python3 -c "import json,sys; print(json.loads(sys.stdin.read()).get('title',''))")
  text=$(echo "$line" | python3 -c "import json,sys; print(json.loads(sys.stdin.read()).get('tweet_text',''))")
  url=$(echo "$line" | python3 -c "import json,sys; print(json.loads(sys.stdin.read()).get('reply_url',''))")
  if [ -z "$title" ] || [ -z "$url" ]; then
    echo "[backfill skip] empty title/url (post_id=$post_id)" | tee -a "$LOG"
    continue
  fi
  COUNT=$((COUNT+1))
  echo "[backfill $COUNT] posting post_id=$post_id ..." | tee -a "$LOG"
  PERSIAN_TMP=$(mktemp /tmp/x_backfill_sns.XXXXXX.md)
  printf 'パターンA（採用推奨）\\n\`\`\`\\n%s\\n\`\`\`\\n' "$text" > "$PERSIAN_TMP"
  BACKFILL_MODE=1 bash "$POSTER" "$title" "$url" "$PERSIAN_TMP" 2>&1 | tee -a "$LOG" | tail -3 || true
  rm -f "$PERSIAN_TMP"
  sleep 90
done < "$QUEUE"
echo "=== x_backfill_runner done $(date -Iseconds) (posted=$COUNT) ===" | tee -a "$LOG"
"""
    OUT_RUNNER.write_text(runner)
    OUT_RUNNER.chmod(0o755)

    print(f"[x_revival] queue: {queued}件 / skip_low_hook: {skipped_low}")
    print(f"  queue file: {OUT_QUEUE}")
    print(f"  runner:     {OUT_RUNNER}")
    print(f"  実行: ENABLE_X_POST=1 bash {OUT_RUNNER}")


if __name__ == "__main__":
    main()
